### ISSUE TITLE
Newest (and working) version is not pushed on npm

### ISSUE THREAD

**Issue by hugohil** [node-dmx/dmx-web#5]
Hey !

Seems like the fix you made with the `node-dmx` require has not been deployed on npm, so when I run `npm i -g dmx-web`, I get an error `Error: Cannot find module '@node-dmx/dmx-library'`.
I just cloned the repo and used the source for now though.

Thanks !

**Comment by sebbean** [comment]
same issue!

**Comment by simonbuehler** [comment]
please give it a push, same error here!

**Comment by wiedi** [comment]
Published 1.0.1 just now - please try if that fixes this.

**Comment by simonbuehler** [comment]
thanks, works!
